blank_issues_enabled: false
contact_links:
    - name: Bug Report
      about: Create a report to help us improve.
      url: https://github.com/decathlon/dblinter/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5Bname+of+the+scope+e.g.+cluster/base/table%5D+issue+title&projects=decathlon

    - name: Feature Request
      about: Suggest an idea for this project
      url: https://github.com/decathlon/dblinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=%5Bname+of+the+scope+e.g.+cluster/base/table%5D+issue+title&projects=decathlon

    - name: Documentation Request
      about: Need documentation on a component.
      url: https://github.com/decathlon/dblinter/issues/new?assignees=&labels=documentation&template=documentation_request.md&title=%5BDocumentation%5D%5Bname+of+the+scope+e.g.+cluster/base/table%5D+issue+title&projects=decathlon
